on:
  push:
    branches:
      - master
      - main
name: Build Dev
jobs:
  publish:
    strategy:
      matrix:
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - 386
          - arm64
          - arm
        include:
          - os: linux
            arch: amd64
            artifact_name: dasel_linux_amd64
            test_version: true
          - os: linux
            arch: 386
            artifact_name: dasel_linux_386
            test_version: false
          - os: darwin
            arch: amd64
            artifact_name: dasel_darwin_amd64
            test_version: false
          - os: darwin
            arch: arm64
            artifact_name: dasel_darwin_arm64
            test_version: false
          - os: windows
            arch: amd64
            artifact_name: dasel_windows_amd64.exe
            test_version: false
          - os: windows
            arch: 386
            artifact_name: dasel_windows_386.exe
            test_version: false
          - os: linux
            arch: arm64
            artifact_name: dasel_linux_arm64
            test_version: false
          - os: linux
            arch: arm
            artifact_name: dasel_linux_arm32
            test_version: false
        exclude:
          - os: darwin
            arch: 386
          - os: windows
            arch: arm64
          - os: windows
            arch: arm
          - os: darwin
            arch: arm
    name: Dev build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.24.0' # The Go version to download (if necessary) and use.
      - name: Set env
        run: echo RELEASE_VERSION=development >> $GITHUB_ENV
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 go build -o target/release/${{ matrix.artifact_name }} -ldflags="-X 'github.com/tomwright/dasel/v2/internal.Version=${{ env.RELEASE_VERSION }}'" ./cmd/dasel
      - name: Test version
        if: matrix.test_version == true
        run: ./target/release/${{ matrix.artifact_name }} --version
