on: [push, pull_request]

env:
  GOLANG_VERSION: 1 # The Go version to download (if necessary) and use.

name: Container build, test and publish
jobs:
  container:
    strategy:
      fail-fast: false # true
      matrix:
        target-base-image:
          - alpine
          - debian:slim
        include:
          - target-base-image: alpine
            tags: |
              ghcr.io/tomwright/dasel:alpine
              ghcr.io/tomwright/dasel:${{ github.ref_name }}-alpine
          - target-base-image: debian:slim
            tags: |
              ghcr.io/tomwright/dasel:latest
              ghcr.io/tomwright/dasel:${{ github.ref_name }}
              ghcr.io/tomwright/dasel:${{ github.ref_name }}-slim
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and Export
          uses: docker/build-push-action@v5
          with:
            context: .
            load: true
            build-args: | 
              GOLANG_VERSION=${{ env.GOLANG_VERSION }}
              RELEASE_VERSION=${{ github.ref_name }}
              TARGET_BASE_IMAGE=${{ matrix.target-base-image }}
            tags: ${{ matrix.tags }}
        - name: Test
          run: |
            echo '{"hello": "World"}' | docker run -i --rm ghcr.io/tomwright/dasel:latest -r json 'hello'
        - name: Docker login
          if: ${{ startsWith(github.ref, 'refs/tags/v') }}
          run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u TomWright --password-stdin
        - name: Build and Push
          if: ${{ startsWith(github.ref, 'refs/tags/v') }}
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64,linux/arm64
            push: true
            build-args: | 
              GOLANG_VERSION=${{ env.GOLANG_VERSION }}
              RELEASE_VERSION=${{ github.ref_name }}
              TARGET_BASE_IMAGE=${{ matrix.target-base-image }}
            tags: ${{ matrix.tags }}
