on: [push, pull_request]

env:
  GOLANG_VERSION: 1

name: Container build, test and publish
jobs:
  container:
    strategy:
      fail-fast: true
      matrix:
        include:
          - target-base-image: alpine
            tags: |
              ghcr.io/tomwright/dasel:alpine
              ghcr.io/tomwright/dasel:${{ github.ref_name }}-alpine
          - target-base-image: debian:bookworm-slim
            tags: |
              ghcr.io/tomwright/dasel:latest
              ghcr.io/tomwright/dasel:${{ github.ref_name }}
              ghcr.io/tomwright/dasel:${{ github.ref_name }}-bookworm-slim
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and Export
          uses: docker/build-push-action@v5
          with:
            context: .
            load: true
            build-args: | 
              GOLANG_VERSION=${{ env.GOLANG_VERSION }}
              RELEASE_VERSION=${{ github.ref_name }}
              TARGET_BASE_IMAGE=${{ matrix.target-base-image }}
            tags: dasel:test
        - name: Test
          run: |
            echo '{"hello": "World"}' | docker run -i --rm dasel:test -r json 'hello'
        - name: Login to GitHub Container Registry
          if: ${{ startsWith(github.ref, 'refs/tags/v') }}
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: TomWright
            password: ${{ secrets.GHCR_PAT }}
        - name: Build and Push
          if: ${{ startsWith(github.ref, 'refs/tags/v') }}
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64,linux/arm64
            push: true
            build-args: | 
              GOLANG_VERSION=${{ env.GOLANG_VERSION }}
              RELEASE_VERSION=${{ github.ref_name }}
              TARGET_BASE_IMAGE=${{ matrix.target-base-image }}
            tags: ${{ matrix.tags }}
